name: PrepareStaalAIPR

on:
  issues:
    types: [opened]

permissions:
  contents: write         # needed to push a branch and commit
  pull-requests: write    # needed to open a PR
  issues: read            # read the issue payload

jobs:
  create-pr-from-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check out master
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install jq (to parse issue JSON)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Create branch from master
        id: branch
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          SAFE_TITLE=$(echo "${{ github.event.issue.title }}" | tr -cd '[:alnum:]- _' | tr ' ' '-' | tr '[:upper:]' '[:lower:]' | cut -c1-40)
          BRANCH="issue-${ISSUE_NUMBER}-${SAFE_TITLE:-new-issue}-${{ github.run_id }}"
          git checkout -b "$BRANCH"
          echo "branch_name=$BRANCH" >> "$GITHUB_OUTPUT"

      - name: Write lastprompt.txt with full issue JSON
        run: |
          # Extract the .issue object from the event payload and write it to lastprompt.txt
          jq '.issue' "$GITHUB_EVENT_PATH" > lastprompt.txt

          # Also append a human-friendly summary at the top
          {
            echo "### Issue Summary"
            echo "Number: #${{ github.event.issue.number }}"
            echo "Title: ${{ github.event.issue.title }}"
            echo "Author: ${{ github.event.issue.user.login }}"
            echo "URL: ${{ github.event.issue.html_url }}"
            echo "Created: ${{ github.event.issue.created_at }}"
            echo
            echo "Labels: $(printf '%s\n' "${{ toJson(github.event.issue.labels) }}" | jq -r 'map(.name) | join(", ")')"
            echo
            echo "----"
            echo
          } | cat - lastprompt.txt > lastprompt.txt.tmp && mv lastprompt.txt.tmp lastprompt.txt

      - name: Commit and push changes
        run: |
          git add lastprompt.txt
          git commit -m "Add lastprompt.txt for issue #${{ github.event.issue.number }}"
          git push origin "${{ steps.branch.outputs.branch_name }}"

      - name: Create Pull Request to master
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --title "Add lastprompt.txt for issue #${{ github.event.issue.number }}" \
            --body "Auto-generated from [issue #${{ github.event.issue.number }}](${{ github.event.issue.html_url }})." \
            --base master \
            --head "${{ steps.branch.outputs.branch_name }}"
