name: PrepareStaalAIPR

on:
  issues:
    types: [opened]

permissions:
  contents: write         # needed to push a branch and commit
  pull-requests: write    # needed to open a PR
  issues: read            # read the issue payload

jobs:
  create-pr-from-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check out master
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install jq (to parse issue JSON)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Create branch from master
        id: branch
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          SAFE_TITLE=$(echo "${{ github.event.issue.title }}" | tr -cd '[:alnum:]- _' | tr ' ' '-' | tr '[:upper:]' '[:lower:]' | cut -c1-40)
          BRANCH="issue-${ISSUE_NUMBER}-${SAFE_TITLE:-new-issue}-${{ github.run_id }}"
          git checkout -b "$BRANCH"
          echo "branch_name=$BRANCH" >> "$GITHUB_OUTPUT"

      - name: Write lastprompt.txt with issue content
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          {
            echo "Title: ${{ github.event.issue.title }}"
            echo
            echo "Description:"
            echo "${{ github.event.issue.body }}"
            echo
            echo "Comments:"
            gh issue view ${{ github.event.issue.number }} --repo ${{ github.repository }} --comments --json comments --jq '.comments[].body'
          } > lastprompt.txt

      - name: Commit and push changes
        run: |
          git add lastprompt.txt
          git commit -m "Add lastprompt.txt for issue #${{ github.event.issue.number }}"
          git push origin "${{ steps.branch.outputs.branch_name }}"

      - name: Create Pull Request to master
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          gh pr create \
            --title "Add lastprompt.txt for issue #${{ github.event.issue.number }}" \
            --body "Auto-generated from [issue #${{ github.event.issue.number }}](${{ github.event.issue.html_url }})." \
            --base master \
            --head "${{ steps.branch.outputs.branch_name }}"
